repos:
# Common hooks from pre-commit
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Specific tools with their configurations
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

# Common hooks for sorting imports
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort

# Common hooks for running black
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

# Common hooks for running flake8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--ignore=E501,E266,E303,W503']

# Common hooks for checking docstring coverage
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [pipelines, -v, -i, --fail-under=60, '-e', '**/__init__.py']
        pass_filenames: false

# Running 'bandit' to identify common security issues in your Python code.
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: ["-x", "tests/", ""]
